const challenges = {
Truth: [
"What's something you did that you hope no one here ever finds out?",
"Who here intimidates you the most and why?",
"What’s the boldest thought you've had about someone in this group?",
"What’s the biggest secret you're hiding right now?",
"What’s the most manipulative thing you’ve done?",
"What’s the most jealous you’ve ever been?",
"What’s one thing you pretend you don’t care about but actually do?",
"What’s a truth that would shock the group the most?",
"What’s something dark you’ve never confessed?",
"Who here do you feel judged by?",
"Which person here do you find the hardest to read?",
"What’s a lie you told that changed something big?",
"What’s the most shameful reason you liked someone?",
"What’s a fantasy you’d never admit in public?",
"What’s something you wish you didn’t enjoy?",
"Who here would you never want to argue with?",
"What’s the most selfish thing you’ve done?",
"What’s something you regret liking?",
"What’s something risky you wish you had the courage to do?",
"What’s something you envy about someone in this room?",
"What’s a habit you wouldn't want anyone to witness?",
"What’s the pettiest thing you’ve done recently?",
"What’s a memory you’d erase if you could?",
"What’s the most chaotic decision you've ever made?",
"What’s the last time you felt genuinely embarrassed?",
"What’s one thing that instantly makes you nervous?",
"What’s one thing that instantly gets under your skin?",
"What’s the meanest thought you've had today?",
"What’s something you pretended to like for attention?",
"What’s something you said behind someone’s back that you'd never say to their face?",
"What’s something you hate admitting you're afraid of?",
"What’s the biggest red flag you ignore?",
"What’s the cruelest thing you’ve thought but not said?",
"What’s a truth about yourself you keep avoiding?",
"What’s something you hope no one here asks you today?",
"What’s the most awkward attraction you’ve had?",
"What’s the most reckless choice you made for someone you liked?",
"What’s something you want from someone here but won’t say?",
"What’s one thing you're jealous someone else here has?",
"What’s a reason you stopped liking someone that you’d never admit?",
"What’s something embarrassing you’re weirdly proud of?",
"What’s something you wish people assumed about you?",
"What’s the last thing you did that would ruin your image here?",
"What’s one insecurity you hide extremely well?",
"What’s something you hope no one in this room ever witnesses?",
"What’s something you only do when you’re alone?",
"Who here do you think would reject you instantly?",
"What’s something you'd never say sober?",
"What’s something dark that made you laugh?",
"What’s something petty you’d fight someone over?",
"What’s one thing you fake confidence about?",
"What’s an opinion you have that would get you in trouble?",
"What’s a truth that would make everyone here look at you differently?",
"What’s something embarrassing you're still salty about?",
"What’s a moment you replay in your head and cringe?",
"What’s your worst habit in relationships?",
"What’s something you avoid thinking about?",
"What’s one thing you’d do if there were zero consequences?",
"What’s the last time you purposely ignored someone?",
"What’s something you do that you hope looks cooler than it really does?",
"What’s the weirdest reason you’ve liked someone?",
"What’s a compliment you secretly love receiving?",
"What’s something you’re weirdly obsessed with?",
"What’s something embarrassing you thought was attractive?",
"What’s one thing you desperately wish you were better at?",
"What’s a boundary you broke that you regret?",
"What’s something you judge others for?",
"What’s the most awkward compliment you’ve given?",
"What’s something stupid you believed for way too long?",
"What’s a moment you wish you handled differently?",
"What’s something you’re scared to admit you want?",
"What’s a truth that would expose you instantly?",
"What’s a secret that changed how you see yourself?",
"What’s a thought you’re embarrassed you had recently?",
"What’s something risky you almost did?",
"What’s something embarrassing you enjoyed?",
"What’s something you pretended not to notice recently?",
"What’s a moment you wish no one saw?",
"What’s the most awkward crush you’ve ever had?",
"What’s something embarrassing that still haunts you?",
"What’s a time you acted brave but were terrified?",
"What’s a truth that scares you?",
"What’s the pettiest reason you disliked someone?",
"What’s the weirdest thing that made you jealous?",
"What’s something you want but won’t admit?",
"What’s something childish you still secretly love?",
"What’s a truth you think would shock everyone?",
"What’s a thought you had today that you’d never say aloud?",
"What’s something sneaky you’ve done recently?",
"What’s something you know you shouldn't enjoy but do?",
"What’s something you’ve kept hidden for years?",
"What’s one thing you hate when people point out?",
"What’s a rumor about you that was actually true?",
"What’s the real reason you don’t like someone here?",
"What’s something that once embarrassed you but now doesn’t?",
"What’s something huge you’re avoiding dealing with?", 
"What’s a thought you hope no one here can guess?",
"What’s one thing you’d confess if no one could judge you?",
"What’s something you secretly want someone here to ask you?"
],

Physical: [
"Do a 40‑second wall sit.",
"Do a 30‑second plank while making eye contact with someone.",
"Do 20 squats without breaking eye contact with the group.",
"Hold a push-up position for 20 seconds.",
"Spin for 15 seconds and walk straight.",
"Balance on one foot for 25 seconds.",
"Do 15 lunges while naming countries.",
"Do 10 push-ups slowly.",
"Act like you're climbing a ladder for 20 seconds.",
"Do a slow-motion run for 15 seconds.",
"Hold your arms up for 25 seconds.",
"Do 12 jumping jacks silently.",
"Move like a robot for 20 seconds.",
"Do 10 high knees with exaggerated seriousness.",
"Try to touch your toes for 20 seconds.",
"Balance with eyes closed for 10 seconds.",
"Do 10 sumo squats.",
"Do a wall push-up 15 times.",
"Do 20 shoulder rolls dramatically.",
"Pretend you're in slow gravity for 20 seconds.",
"Do 15 calf raises.",
"Do marching steps for 20 seconds.",
"Hop on one foot for 10 seconds.",
"Do 20 seconds of air boxing.",
"Hold a squat for 20 seconds.",
"Do 10 arm circles forward and backward.",
"Do 10 side-to-side hops.",
"Do 15 tricep dips on a chair.",
"Hold a yoga pose for 20 seconds.",
"Crawl like a bear for 10 seconds.",
"Move like you're sneaking past lasers for 15 seconds.",
"Do 10 frog jumps.",
"Do a dramatic stretch routine.",
"Do a slow-motion fall and recovery.",
"Do 20 seconds of shadow wrestling.",
"Act like you're pulling a heavy rope for 15 seconds.",
"Balance with one foot in front of the other for 15 seconds.",
"Do 10 backward steps dramatically.",
"Act like you’re dodging invisible projectiles.",
"Do 15 butt kicks.",
"Do 10 controlled deep squats.",
"Hold a reverse plank for 15 seconds.",
"Do 15 big exaggerated steps.",
"Walk like you're on a runway.",
"Do 10 quick direction changes.",
"Do 15-second power stance.",
"Do 10 burpee-lite versions (no push‑up).",
"Do seated leg lifts for 20 seconds.",
"Do 15 hip circles.",
"Do 10 wall taps with your foot.",
"Do 15 seconds of intense statue pose.",
"Try to do a cartwheel motion without actually cartwheeling.",
"Do 10 arm pumps like a bodybuilder.",
"Act like you're swimming on land for 15 seconds.",
"Do 20 toe taps.",
"Do 10 roll-down spine stretches.",
"Act like you're pushing a heavy object for 15 seconds.",
"Do 15 neck stretches slowly.",
"Do 10 deep lunges.",
"Do 12-second plank with one leg lifted.",
"Do 20 seconds of controlled breathing with posture.",
"Do 10 explosive jumps (moderate height).",
"Do 15 glute squeezes standing.",
"Do 10 backward lunges.",
"Hold a low lunge for 15 seconds.",
"Do 12 shoulder presses without weights.",
"Do 20 seconds of imaginary rope skipping.",
"Do 10 mini‑sprints on the spot.",
"Move like you're in slow-motion water.",
"Do 15 forward bends.",
"Do 10 side bends each side.",
"Do 15 chest expansions.",
"Balance one foot on your other knee for 15 seconds.",
"Do a 10-second plank variation.",
"Do 10 baby burpees.",
"Do 20 seconds of intense stomping.",
"Do 10 hand-to-knee taps.",
"Do 15 seated twists.",
"Walk backward for 15 seconds.",
"Do 20 seconds of skipping motion.",
"Do 10 diagonal lunges.",
"Hold a strong stretch pose.",
"Do 12 squat pulses.",
"Do 10 leg swings.",
"Do 20 seconds of “run in place silently.”",
"Do 10 wall slides.",
"Do 15-second dramatic bodybuilding poses.",
"Do 10 careful abs contractions.",
"Do 15 seated marches.",
"Do 10 slow squats with pauses.",
"Do 15 wrist circles.",
"Do 20-second freeze poses.",
"Do 12 balance lunges.",
"Hold your arms wide for 20 seconds.",
"Do 10 slow high kicks.",
"Do 15 exaggerated breaths.",
"Do 10 power walks in a circle.",
"Hold a superman pose for 12 seconds.",
"Do 10 sideways crab walks for 8 steps.",
"Act like you're escaping invisible vines."
],

Food: [
"Eat a spoonful of the spiciest thing available.",
"Eat a weird combo chosen by the group.",
"Eat something with your eyes closed.",
"Let someone pick a random food for you.",
"Eat something without using your hands.",
"Take the smallest scary bite of something intense.",
"Eat something while holding your breath.",
"Let someone mix two random sauces for you.",
"Eat something bitter with no reaction.",
"Eat something sour and keep a straight face.",
"Let someone make you a tiny mystery bite.",
"Eat two things that should not go together.",
"Try to guess what you’re eating blindfolded.",
"Drink a mix of three random ingredients.",
"Eat something cold, then something hot.",
"Chew something loudly for 5 seconds.",
"Let someone feed you a random bite.",
"Eat something while someone distracts you.",
"Take a bite of something unusual in the room.",
"Let someone season a random piece of food.",
"Eat something spicy then whisper 'perfect'.",
"Take a small bite of the weirdest thing in the kitchen.",
"Eat something without chewing for 3 seconds.",
"Let someone pick the temperature—hot or cold.",
"Take a bite while someone counts loudly.",
"Eat something with your non-dominant hand.",
"Let the group decide how big your bite is.",
"Eat something while looking someone dead in the eyes.",
"Eat something while pretending it's delicious.",
"Eat two foods in the wrong order.",
"Take a bite of something while spinning slowly.",
"Eat something and describe it dramatically.",
"Let someone choose a random condiment for you.",
"Combine something salty and sweet.",
"Eat something while blindfolded for 15 seconds.",
"Eat something while acting like a chef.",
"Let someone roll a food item across the table to you.",
"Eat something while keeping back perfectly straight.",
"Eat something as silently as possible.",
"Take the tiniest bite allowed.",
"Take the biggest bite allowed.",
"Let someone blow on your bite to cool it.",
"Eat something while keeping your face expressionless.",
"Eat something while someone narrates you.",
"Eat something after smelling it first.",
"Let the group pick your next flavor.",
"Eat something that starts with the letter chosen.",
"Eat something while someone counts backwards.",
"Eat something cold after something warm.",
"Let someone shake a container and you choose blind.",
"Eat something in slow motion.",
"Eat something while acting scared.",
"Eat something while acting overly confident.",
"Let someone pick how fast you should chew.",
"Eat something while humming.",
"Eat something and describe it like a love letter.",
"Eat two bites as if they taste opposite.",
"Eat something bitter gently.",
"Eat something sweet aggressively.",
"Let someone swirl food before giving it to you.",
"Eat something ‘mystery-style’.",
"Eat something while maintaining eye contact.",
"Eat something while making it look dramatic.",
"Let group choose spicy or sour.",
"Eat something from the smallest plate.",
"Eat a bite dramatically slow.",
"Eat something while pretending it’s disgusting.",
"Eat something while pretending it's heavenly.",
"Eat something while the group stares silently.",
"Eat something while you try not to blink.",
"Eat something after shaking your head.",
"Eat something while tapping your foot.",
"Eat something with fingers only.",
"Eat something with exaggerated elegance.",
"Eat something and whisper the flavor.",
"Eat something while trying not to laugh.",
"Eat something facing away from the group.",
"Eat something with your eyes wide open.",
"Eat something like it's your first time eating.",
"Eat two textures back-to-back.",
"Eat something while pretending you're on camera.",
"Eat something while doing a pose.",
"Eat something while someone claps slowly.",
"Eat something with your weaker hand.",
"Eat something while leaning left.",
"Eat something while leaning right.",
"Eat something while shaking your head 'no'.",
"Eat something while nodding 'yes'.",
"Eat something and guess calories.",
"Eat something cold without reacting.",
"Eat something spicy without blinking.",
"Eat something while describing the texture.",
"Eat something that makes you flinch.",
"Eat something then describe it in one word.",
"Eat something without looking at it.",
"Eat something with a countdown.",
"Eat something and pretend you hate food.",
"Eat something and pretend you're obsessed with food."
],

Random: [
"Give an overly dramatic speech about nothing.",
"Talk like a movie villain for one round.",
"Describe someone here as if narrating a documentary.",
"Pretend you're in slow motion for 10 seconds.",
"Speak in an accent for the next 2 rounds.",
"Narrate everything you do for 15 seconds.",
"Make direct eye contact with someone and say nothing for 10 seconds.",
"Say the next sentence in dramatic whisper.",
"Describe your day as a horror movie.",
"Switch seats with someone randomly.",
"Say a weird fact confidently.",
"Talk like you’re in a commercial for 15 seconds.",
"Pretend you’re hiding a huge secret.",
"Say something completely out of context with confidence.",
"Talk like a robot for 10 seconds.",
"Act as if someone here is your enemy for 15 seconds.",
"Act like you smelled something suspicious.",
"Say a dramatic line from an imaginary movie.",
"Pretend to write an invisible letter.",
"Announce your presence like royalty.",
"Act like you’re sneaking through lasers.",
"Act like the floor is too hot.",
"Introduce yourself like a celebrity.",
"Pretend you’re doing a magic spell.",
"Say something deep but completely meaningless.",
"Talk like you're being interviewed.",
"Announce a fake weather forecast.",
"Pretend someone here owes you money.",
"Say the most random sentence possible.",
"Make up a fake new law.",
"Pretend you're mind-reading someone.",
"Act like someone's bodyguard.",
"Say something extremely suspicious.",
"Describe someone like a detective.",
"Pretend you're teaching a class.",
"Say something like you're plotting revenge.",
"Talk like you’re hiding from paparazzi.",
"Act offended by something tiny.",
"Invent a ritual and perform it.",
"Describe the room dramatically.",
"Talk like you're in a spy movie.",
"Pretend you're being recorded secretly.",
"Say something mysterious.",
"Act like you're in slow panic.",
"Say something as if it's your last words.",
"Act like you're tracking someone.",
"Talk like you're in medieval times.",
"Announce breaking news dramatically.",
"Say something cryptic to the group.",
"Act like you discovered something huge.",
"Pretend to negotiate with an alien.",
"Act like you're summoning courage.",
"Say something wise but confusing.",
"Pretend someone betrayed you.",
"Act like you're sending a secret signal.",
"Accuse someone of something absurd.",
"Pretend you're searching for clues.",
"Talk like you're in a noir film.",
"Make up a prophecy.",
"Describe yourself like a villain origin story.",
"Talk like you’re underwater.",
"Act offended dramatically.",
"Announce a fake emergency.",
"Give someone a new nickname on the spot.",
"Talk like you're in a video game.",
"Describe a random object like it's valuable.",
"Make up a conspiracy theory.",
"Act like something tiny scared you.",
"Pretend to decode a message.",
"Speak like you're holding back a laugh.",
"Act like you're preparing for battle.",
"Narrate someone’s movement seriously.",
"Talk like an evil mastermind.",
"Say something you’d whisper dramatically.",
"Announce a fake prediction.",
"Talk like you're giving a TED talk.",
"Pretend someone here is famous.",
"Say something with intense seriousness.",
"Act like you're trying to remember something important.",
"Act like someone stole something of yours.",
"Say something poetic unexpectedly.",
"Act like you’re in a courtroom.",
"Describe your emotions like a sport commentator.",
"Act like you're in a time loop.",
"Talk like you’re extremely suspicious.",
"Pretend to translate an alien language.",
"Act like everything you see is confusing.",
"Give someone a dramatic warning.",
"Describe your thoughts in third person.",
"Act like you're undercover.",
"Talk like you’re exhausted from a long journey.",
"Describe someone as if they’re legendary.",
"Act like you're solving a murder mystery.",
"Say something disturbing but vague.",
"Pretend you're holding an invisible treasure.",
"Act like you're lost in a maze.",
"Talk like you're writing a diary entry."
],

Adult: [
"If you had to choose someone here for a romantic weekend, who would it be?",
"Stare into someone’s eyes for 12 seconds without laughing.",
"Say the most flirtatious line you can think of.",
"Describe the type of person you’re weak for.",
"Say something charming with a straight face.",
"Reveal a subtle detail you find attractive in people.",
"Describe your ideal slow-burn connection.",
"Say a line you'd use to impress someone in private.",
"Describe a moment that would've been romantic if timing was different.",
"Say one thing you find irresistible in a person.",
"Say who here gives off the strongest 'dangerously attractive' vibe.",
"Pick someone and say what first impression they give.",
"Say something someone once did that made you flustered.",
"Describe a look someone can give that weakens you.",
"Say how you act when you’re secretly into someone.",
"Say the boldest compliment you know.",
"Describe the exact moment you start catching feelings.",
"Say one thing you notice first when attracted.",
"Describe an ideal almost-romantic situation.",
"Say what kind of confidence you find attractive.",
"Say who here has the best voice.",
"Say something you’ve always wanted to hear from someone.",
"Describe the subtle ways you flirt.",
"Say what makes someone dangerously charming.",
"Say who here you’d trust with a personal secret.",
"Describe a moment you got unexpectedly flustered.",
"Say one thing that always gives you butterflies.",
"Pick someone and describe the vibe they give.",
"Say who here looks like trouble in a good way.",
"Describe how someone could easily win you over.",
"Say one thing that makes someone irresistible.",
"Say who here seems the most mysterious in an attractive way.",
"Describe a moment where tension felt unreal.",
"Say one thing you secretly wish someone here would say to you.",
"Say what you think someone here is hiding about their charm.",
"Describe your most flustering compliment received.",
"Say who here gives off a secretly soft side.",
"Say one trait that instantly draws you in.",
"Describe a vibe you can't resist.",
"Say what small gesture from someone can make your day.",
"Say which type of look melts you instantly.",
"Describe the last time someone caught you off guard emotionally.",
"Say who here has the most magnetic energy.",
"Describe a scenario that would leave you speechless.",
"Say a subtle thing someone could do that would fluster you.",
"Describe a moment that would've been romantic if extended.",
"Say which type of confidence scares you in a good way.",
"Say something bold but still classy.",
"Pick someone and give a tasteful compliment.",
"Describe an unintentional attractive moment.",
"Say who here you think would surprise you emotionally.",
"Describe one thing that's unintentionally attractive.",
"Say one type of attention that affects you too much.",
"Say what someone could whisper that would ruin your composure.",
"Describe a romantic cliché you secretly like.",
"Say who here seems like they give the best hugs.",
"Describe someone’s ‘dangerous charm’ respectfully.",
"Say what someone here could say that would fluster you instantly.",
"Describe how you act around someone you're drawn to.",
"Say one thing you wish someone noticed about you.",
"Pick someone silently and give them a knowing nod.",
"Say one compliment you're too shy to give normally.",
"Pick someone and describe their aura.",
"Say what kind of presence makes you nervous in a good way.",
"Describe a moment you almost said something bold.",
"Say which type of personality melts your guard.",
"Describe a hypothetical moment that'd be intense.",
"Say one thing that'd make you blush instantly.",
"Say who here gives a mysterious warm vibe.",
"Describe a situation that would've been charged with tension.",
"Say what kind of confidence is too much for you.",
"Describe the last time you felt shy unexpectedly.",
"Say who here seems like they'd be surprisingly gentle.",
"Describe what subtle flirting looks like to you.",
"Say one thing that makes you weak when said right.",
"Say which vibe you fall for most easily.",
"Describe your ‘danger zone’ type of attraction.",
"Pick someone and tell them one classy bold line.",
"Say what kind of eye contact breaks you.",
"Describe the perfect almost-kiss moment (clean version).",
"Say one thing that someone could wear that'd distract you.",
"Say who here you think would give dangerous chemistry.",
"Describe a moment that would've changed everything if someone leaned in.",
"Say what kind of attention is impossible to ignore.",
"Say one thing that always gets to you emotionally.",
"Say who here has the strongest silent presence.",
"Describe something soft that catches you off guard.",
"Say what type of person you'd never admit you're attracted to.",
"Pick someone and say the first vibe they gave you.",
"Describe how someone could ruin your composure with one sentence.",
"Say who here you think would give great emotional tension.",
"Describe someone you once underestimated but found attractive later.",
"Say one bold thing you've thought but never said.",
"Describe the most flustering 'almost' moment you've had.",
"Say one thing someone here does that could be unintentionally attractive."
],

Social: [
"Give a genuine compliment to the person to your right.",
"Say a funny fact about yourself.",
"Say something you appreciate about someone here.",
"Tell a short story involving someone in the group.",
"Give someone a new nickname.",
"Describe someone as if they’re a legend.",
"Say who here gives the calmest vibe.",
"Say something positive about the person across from you.",
"Tell the group one thing you're proud of.",
"Introduce someone like a hype announcer.",
"Say something encouraging to the group.",
"Describe someone like you're narrating a documentary.",
"Say something you admire in someone's personality.",
"Give someone a title (e.g., 'CEO of…').",
"Say which person you'd trust in an emergency.",
"Give a small roast (friendly).",
"Say what role each person would have in a movie.",
"Tell someone the first vibe they gave you.",
"Say who has the most chaotic energy.",
"Give someone a prediction for their future.",
"Say who here seems like the best secret keeper.",
"Tell someone what animal they'd be.",
"Say something cool about the group.",
"Describe someone like they’re in a video game.",
"Give someone a fake award.",
"Say who you’d pick as a teammate.",
"Give someone a mysterious compliment.",
"Say who looks like they always have a plan.",
"Give someone a one‑sentence pep talk.",
"Tell someone the funniest vibe they give you.",
"Say who seems like the undercover mastermind.",
"Describe someone as if you’re their lawyer.",
"Say what someone would be famous for.",
"Give someone a secret agent name.",
"Say who has main-character energy.",
"Give someone a dramatic backstory.",
"Say who you’d trust with directions.",
"Give someone a royal title.",
"Describe someone like a movie trailer.",
"Say who would survive a zombie apocalypse.",
"Give someone a compliment with only 3 words.",
"Say who looks the most unpredictable.",
"Give someone a creative superpower.",
"Say who would make a great mentor.",
"Describe someone like you're an announcer.",
"Say who has the most ‘mysterious aura’.",
"Give someone a supportive message.",
"Say who here has the funniest timing.",
"Give someone a mythological title.",
"Say who would win in a logic contest.",
"Describe someone like they’re in a novel.",
"Say something inspiring to a player.",
"Give someone an aesthetic (vibe).",
"Say who has the strongest intuition.",
"Give someone a movie genre.",
"Say who would run the best kingdom.",
"Give someone a random prophecy.",
"Say who you’d want as a partner in crime.",
"Give someone one piece of advice.",
"Say who looks like they'd start a revolution.",
"Give someone a symbolic animal.",
"Say who would be a great leader.",
"Describe someone like a detective.",
"Say something uplifting about the group.",
"Give someone a dramatic title.",
"Say who has the boldest energy.",
"Give someone a fictional power‑up.",
"Say who looks like they hold deep secrets.",
"Describe someone like you're narrating destiny.",
"Say who here has the sharpest instincts.",
"Give someone a poetic compliment.",
"Say who looks like they'd control a kingdom.",
"Give someone a futuristic role.",
"Say who would run the best café.",
"Describe someone using only metaphors.",
"Say who looks like they'd survive any chaos.",
"Give someone a warrior title.",
"Say who here has the kindest aura.",
"Give someone a dramatic reveal phrase.",
"Say who would be a great captain.",
"Give someone an elemental power.",
"Say who would be the best strategist.",
"Give someone a cosmic compliment.",
"Say who would be best at negotiating.",
"Give someone a mysterious warning.",
"Say who would make a good hero.",
"Describe someone like they’re a prophecy.",
"Say something encouraging to the next player.",
"Give someone a dramatic nickname.",
"Say who looks like they'd win a challenge.",
"Give someone an aura color.",
"Say who has chaotic good energy.",
"Give someone a vibe label.",
"Say who seems like a natural leader.",
"Give someone a destiny role.",
"Say who here would survive the longest in unknown lands.",
"Give someone a poetic title.",
"Say who has the strongest presence.",
"Give someone a supportive compliment."
],

};

let players = [];

document.getElementById("addPlayerBtn").onclick = () => {
    const name = document.getElementById("playerInput").value.trim();
    if (name === "") return;

    players.push(name);

    const tag = document.createElement("span");
    tag.textContent = name;
    document.getElementById("playerList").appendChild(tag);

    document.getElementById("playerInput").value = "";

    buildPlayerWheel();
};
document.addEventListener("keydown", (e) => {
    if (e.code === "Enter") {
        document.getElementById("addPlayerBtn").onclick();
    }
});

function buildPlayerWheel() {
    const wheel = document.getElementById("wheel");
    wheel.innerHTML = ""; // Clear previous segments

    const count = players.length;
    if (count === 0) return;

    const segmentAngle = 360 / count;

    for (let i = 0; i < count; i++) {

        // Text-only segment (no background)
        let seg = document.createElement("div");
        seg.classList.add("segment");
        seg.textContent = players[i];

        seg.style.transform =
            `rotate(${i * segmentAngle}deg) skewY(${-(90 - segmentAngle)}deg) rotate(${segmentAngle / 2}deg)`;

        wheel.appendChild(seg);

        // Separator line
        let line = document.createElement("div");
        line.classList.add("separator");
        line.style.transform = `rotate(${i * segmentAngle}deg)`;
        wheel.appendChild(line);
    }
}

function pickRandom(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
}

function showChallenge(player, text) {
    const box = document.getElementById("challengeBox");
    box.style.opacity = 0;
    setTimeout(() => {
        box.innerHTML = `<b>${player}</b>: ${text}`;
        box.style.opacity = 1;
    }, 300);
}

document.getElementById("spinBtn").onclick = () => {
    if (players.length === 0) return alert("Add at least one player.");

    let spinAmount = 720 + Math.random() * 360;
    const wheel = document.getElementById("wheel");
    wheel.style.transform = `rotate(${spinAmount}deg)`;

    setTimeout(() => {
        const count = players.length;
        const anglePerPlayer = 360 / count;

        const landedAngle = spinAmount % 360;
        const selectedIndex = Math.floor(landedAngle / anglePerPlayer);
        const player = players[count - 1 - selectedIndex] || players[0];

        const cat = document.getElementById("categorySelect").value;
        const challenge = pickRandom(challenges[cat]);

        showChallenge(player, challenge);
    }, 2600);
};

document.addEventListener("keydown", (e) => {
    if (e.code === "Space") {
        document.getElementById("spinBtn").click();
    }
});
